Added more fields and added the options for goals
kodiri/fit-your-goal pull request #13
Opened 2018-12-14 09:44 UTC by maruntav

As Ricardo predicted, there seem to be conflicts on the getStarted.js which is my mistake. I wrote the tests but after I wrote the code but it is better than nothing.

2018-12-14 11:24 UTC, rmallols requested changes

2018-12-14 11:24 UTC, rmallols commented on src/getStarted.test.js
> +import GetStartedPage from './getStarted';
This is pretty cool, nice one!

2018-12-14 11:24 UTC, rmallols commented on src/getStarted.js
> +import React, { Component } from 'react';
The file looks nice, but it has an structural problem: it's huge!!! This causes readability issues and, in the long term, you're likely to have git conflicts on it too.

I can suggest two types of refactoring:

1) (Ideal): Split the `GetStarted` logic into smaller components (and files), e.g.:
```
GetStarted
    GetStartedHeader
    GetStartedDropdown
    ...
```

2) (Still OK): Move the majority of the business logic to a new file, with a bunch of JS functions, `getStartedUtils.js`:

```
updateFields
validateGoalsOptions
...
```

Also, a subtle detail. Because this is a react component, please capitalise the file name.

2018-12-17 11:59 UTC, rmallols requested changes

2018-12-17 11:59 UTC, rmallols commented on src/get-started/dropdown/DefaultDropdown.js
> +import React from 'react';
Could you split line 4 please?

e.g.

```
<option 
    style={{display: startUtils.displayGoalDefaultOrNot(this.state.goalOptionVal)}}
    value='instruction'>
```

2018-12-17 11:59 UTC, rmallols commented on src/get-started/get-started-utils/GetStartedUtils.js
> +export {createEmptyFieldObj, everythingFilled, validateGoalsOptions, displayGoalDefaultOrNot, kebabCaseToWords, updateFields, checkIfEverythingIsGood};
Could you please add the `export` prefix inline with the functions?

e.g. `export function createEmptyFieldObj`

That will help to understand the module's API

2018-12-18 14:49 UTC, maruntav commented
Made a new pull request after I made the changes, so I will close it.

2018-12-18 14:49 UTC, closed without merging